### ISSUE TITLE
Can't connect to laravel forge via cli ( cURL error 60: SSL certificate problem: unable to get local issuer certificate )

### ISSUE THREAD

**Issue by WaleedAlrashed** [laravel/forge-cli#52]
- Forge CLI Version: 1.3.4
- PHP Version: 8.0.11

### Description:
Trying to connect to Laravel forge via CLI fails on both `forge login`  and `forge login --token=MY_PERSONAL_TOKEN`

producing the following error:

>  An unexpected error occurred. Please report this issue here:
>   https://github.com/laravel/forge-cli/issues/new/choose
> 
>   - Forge CLI Version: 1.3.4
>   - PHP Version: 8.0.11
>   - Operating System: WINNT
>   - Error Message: cURL error 60: SSL certificate problem: unable to get local issuer certificate (see https://curl.h
>   axx.se/libcurl/c/libcurl-errors.html) for https://forge.laravel.com/api/v1/servers.

### Steps To Reproduce:

`forge login `

produces this aforementioned error.

![image](https://user-images.githubusercontent.com/20885525/153551699-81515905-807d-493e-ad5d-3df6eaadc234.png)

**Comment by nunomaduro** [comment]
We sometimes see this when there is a problem with our customer's DNS settings on their local machine. Can you try using Google Public DNS? The Google Public DNS IP addresses (IPv4) are as follows:

- 8.8.8.8
- 8.8.4.4

Please let us know how it goes.

**Comment by Maximus1000** [comment]
I had this same error on Windows10 today:
An unexpected error occured. Please report this issue here:
  https://github.com/laravel/forge-cli/issues/new/choose

  - Forge CLI Version: 1.7.0
  - PHP Version: 8.1.3
  - Operating System: WINNT
  - Error Message: cURL error 60: SSL certificate problem: unable to get local issuer certificate (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) for https://forge.laravel.com/api/v1/servers.

I confirmed my DNS servers on local machine are listing Google as noted by previous suggestion.
Solution for me was to try running forge login from vagrant, success, API token accepted on vagrant but not on Windows 10 host.
