### ISSUE TITLE
Api Error

### ISSUE THREAD

**Issue by mauriciodulce** [laravel/forge-cli#79]
### Forge CLI Version

1.8.0

### PHP Version

8.2.12

### Description

 Retrieving The List Of Servers

  An unexpected error occured. Please report this issue here:
  https://github.com/laravel/forge-cli/issues/new/choose

  - Forge CLI Version: 1.8.0
  - PHP Version: 8.2.12
  - Operating System: Darwin
  - Error Message: {
      "message": "Server Error"
  }.

### Steps To Reproduce

forge server:list

**Comment by hmennen90** [comment]
This also occurs with forge ssh and forge:server:switch.

PHP 8.3.0 too

  An unexpected error occured. Please report this issue here:  
  https://github.com/laravel/forge-cli/issues/new/choose       
                                                               
  - Forge CLI Version: 1.8.0                                   
  - PHP Version: 8.3.0                                         
  - Operating System: Darwin                                   
  - Error Message: {                                           
      "message": "Server Error"                                
  }.

**Comment by jbrooksuk** [comment]
This should now be resolved. Sorry about that!
